# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a33391f6c93260c66bc81a276c437fbb96a9704da40d8c009ad5eb0d9b1fa8801a520a23e5baf819f129d003cc01770666c4ec1fd6f6fcfb244626b96f97b166

test:
  secret_key_base: d1b55892271b88170e736644b861de30025412e6ff9d45fa90eaef9e90ac3c321821d917e130345a0a895a11fe5dacb6e3c8baf918d8c3e33a813fad733ad584

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
